MvcApplication3/Models/Kategori.cs
using System;
using System.Collections.Generic;

namespace MvcApplication3.Models
{
    public partial class Kategori
    {
        public Kategori()
        {
            this.Etkinliks = new List<Etkinlik>();
            this.SiteTakips = new List<SiteTakip>();
        }

        public int Id { get; set; }
        public string Adi { get; set; }
        public virtual ICollection<Etkinlik> Etkinliks { get; set; }
        public virtual ICollection<SiteTakip> SiteTakips { get; set; }
    }
}

MvcApplication3/Controllers/KategoriController.cs
using MvcApplication3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcApplication3.Controllers
{
    public class KategoriController : Controller
    {
        //
        // GET: /Kategori/

        etkinlikContext etkinlik = new etkinlikContext();

        public ActionResult Index(int id)
        {
        
            return View(id);
        }
        public ActionResult Etkinlistele(int id)
        {
            var data = etkinlik.Etkinliks.Where(x => x.KategoriID == id);
            return View("EtkinlikListele",data);
        }
    }
}

MvcApplication3/Controllers/YonetimController.cs
using MvcApplication3.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcApplication3.Controllers
{
    using Models;
    [Authorize(Roles="Admin")] //Admin yetkilendirme..
    
    public class YonetimController : Controller
    {
        //
        // GET: /Yonetim/
        etkinlikContext etkinlik = new etkinlikContext();
        public ActionResult Index()
        {
            ViewBag.tip = 1;
            return View(etkinlik.Etkinliks.ToList());
        }
        public ActionResult EtkinlikYaz()
        {
            ViewBag.tip = 1;
            ViewBag.Kategoriler = etkinlik.Kategoris.ToList();
            return View();
        }
        [HttpPost]
        public ActionResult EtkinlikYaz(Etkinlik etk1,HttpPostedFileBase Resim,string etiketler)
        {
            if (etk1 != null)
            {
                Kullanici aktif=Session["Kullanici"] as Kullanici;
                etk1.YayimTarih = DateTime.Now;
                etk1.EtkinliTipID = 1;
                etk1.YazarID = aktif.Id;
                etk1.KapakResimID = ResimKaydet(Resim,HttpContext);
                etkinlik.Etkinliks.Add(etk1);
                etkinlik.SaveChanges();

                string[] etikets = etiketler.Split(',');
                foreach (string etiket in etikets)
                {
                    Etiket etk = etkinlik.Etikets.FirstOrDefault(x => x.Adi.ToLower() == etiket.ToLower().Trim());
                    if (etk == null)
                    {
                        etk=new Etiket();
                        etk.Adi = etiket;
                        etkinlik.Etikets.Add(etk);
                        etkinlik.SaveChanges();
     
                    }
                        etk1.Etikets.Add(etk);
                        etkinlik.SaveChanges();
                   
                }

            }
            return RedirectToAction("Index");
        }

        public static int ResimKaydet(HttpPostedFileBase Resim,HttpContextBase ctx)
        {
            etkinlikContext etkinlik = new etkinlikContext();
            
            int kucukWidth = Convert.ToInt32(ConfigurationManager.AppSettings["kw"]);
            int kucukHeight = Convert.ToInt32(ConfigurationManager.AppSettings["kh"]);
            int ortaWidth = Convert.ToInt32(ConfigurationManager.AppSettings["ow"]);
            int ortaHeight = Convert.ToInt32(ConfigurationManager.AppSettings["oh"]);
            int buyukWidth = Convert.ToInt32(ConfigurationManager.AppSettings["bw"]);
            int buyukHeight = Convert.ToInt32(ConfigurationManager.AppSettings["bh"]);

            string newName = Path.GetFileNameWithoutExtension(Resim.FileName) + Guid.NewGuid() + Path.GetExtension(Resim.FileName);

            Image orjRes = Image.FromStream(Resim.InputStream);
            Bitmap kucukRes = new Bitmap(orjRes, kucukWidth, kucukHeight);
            Bitmap ortaRes = new Bitmap(orjRes, ortaWidth, ortaHeight);
            Bitmap buyukRes = new Bitmap(orjRes);

            kucukRes.Save(ctx.Server.MapPath("~/Content/Resimler/Kucuk/"+newName));
            ortaRes.Save(ctx.Server.MapPath("~/Content/Resimler/Orta/" + newName));
            buyukRes.Save(ctx.Server.MapPath("~/Content/Resimler/Buyuk/" + newName));

            Kullanici k = (Kullanici)ctx.Session["Kullanici"];

            Resim dbRes = new Resim();
            dbRes.Adi = Resim.FileName;
            dbRes.BuyukResimYol = "/Content/Resimler/Buyuk/" + newName;
            dbRes.OrtaResimYol = "/Content/Resimler/Orta/" + newName;
            dbRes.KucukResimYol = "/Content/Resimler/Kucuk/" + newName;

            dbRes.EklenmeTarihi = DateTime.Now;
            dbRes.EkleyenID = k.Id;

            etkinlik.Resims.Add(dbRes);
            etkinlik.SaveChanges();

            return dbRes.Id;
        }

        public ActionResult Kategori()
        {
            ViewBag.Tip = 1;
            return View(etkinlik.Kategoris.ToList());
        }
        public ActionResult KategoriEkle()
        {
            ViewBag.Tip = 1;
            return View();
        }
        [HttpPost]
        public ActionResult KategoriEkle(Kategori kat)
        {
            etkinlik.Kategoris.Add(kat);
            etkinlik.SaveChanges();
            return RedirectToAction("Kategori");
        }
        public ActionResult KategoriDuzenle(int id)
        {
            ViewBag.Tip = 1;
            return View(etkinlik.Kategoris.FirstOrDefault(x=>x.Id == id));
        }
        [HttpPost]
        public ActionResult KategoriDuzenle(Kategori kat)
        {
            etkinlik.Entry(kat).State = System.Data.EntityState.Modified;
            etkinlik.SaveChanges();
            return RedirectToAction("Kategori");
        }
        public ActionResult KategoriSil(int id)
        {
            etkinlik.Kategoris.Remove(etkinlik.Kategoris.FirstOrDefault(x=>x.Id==id));
            etkinlik.SaveChanges();
            return RedirectToAction("Kategori");

        }
        [Authorize(Roles="Admin")]
        public ActionResult Rol()
        {

            return View();
        }
    }
}

MvcApplication3/Views/Yonetim/EtkinlikYaz.cshtml
@{
    ViewBag.Title = "EtkinlikYaz";
}

<h2>Yeni Etkinlik Oluştur</h2>
<div class="tabs-top">
                            <ul class="nav nav-tabs">
                                <li class="active"><a href="#top-tab1" data-toggle="tab">Metin</a></li>
                                <li><a href="#top-tab2" data-toggle="tab">Resim</a></li>
                                
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane active" id="top-tab1">
@using (Html.BeginForm("EtkinlikYaz", "Yonetim", FormMethod.Post, new { enctype="multipart/form-data" }))
{ 
    <table>
        <tr>
            <td>Başlık</td>
            <td>
                <input class="form-control" type="text" name="Baslik" value="" placeholder="Başlık giriniz" />
            </td>
        </tr>
        <tr>
            <td>Kategori</td>
            <td>
                <select class="form-control" name="KategoriID">
                    @foreach (var kategori in ViewBag.Kategoriler)
                    { 
                    <option  value="@kategori.Id">
                        @kategori.Adi
                    </option>
                    }

                </select>
            </td>
        </tr>
        <tr>
            <td>Etiketler</td>
            <td><input class="form-control" type="text" name="etiketler" value="" /></td>

        </tr>
        <tr> 
            <td>Resim</td>
            <td>
                <input class="form-control" type="file" name="Resim" value="" />
            </td>

        </tr>
        <tr>
            <td>İçerik</td>
            <td><textarea class="form-control" name="Icerik" placeholder="etkinlik içerigini giriniz" cols="20" rows="10">


                </textarea>


            </td>           
        </tr>
        <tr>
            <td></td>
            <td>
                <input class="form-control" type="submit" name="btnEkle" value="Kaydet" />

            </td>

        </tr>
    </table>



}
                                </div>
                                <div class="tab-pane" id="top-tab2">

                                    Galeri
                                </div>
                                
                            </div>
                        </div>

MvcApplication3/Views/Yonetim/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@model IEnumerable<MvcApplication3.Models.Etkinlik>
<h2>Etkinlikler</h2>

<table class="table">
    <tr>
        <th>Başlık</th>
        <th>Yazar</th>
        <th>Kategori</th>
        <th>Yayım Tarihi</th>

        <th></th>
     </tr>
    @foreach (var item in Model)
    {
      <tr>
        <td>@item.Baslik</td>
        <td>@item.Kullanici.Adi @item.Kullanici.Soyadi</td>
        <td>@item.Kategori.Adi</td>  
        <td>@item.YayimTarih</td>
        <td></td> 
      </tr>
    }
    

</table>

MvcApplication3/Views/Yonetim/Kategori.cshtml
@model IEnumerable<MvcApplication3.Models.Kategori>

@{
    ViewBag.Title = "Kategori";
}

<h2>Kategori</h2>

<p>
    @Html.ActionLink("Yeni Kategori Eklemek için Tıklayın..", "KategoriEkle")
</p>
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Adi)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Adi)
        </td>
        <td>
            @Html.ActionLink("Düzenle", "KategoriDuzenle", new { id=item.Id }) |
            
            @Html.ActionLink("Sil", "KategoriSil", new { id=item.Id })
        </td>
    </tr>
}

</table>

MvcApplication3/Views/Yonetim/KategoriDuzenle.cshtml
@model MvcApplication3.Models.Kategori

@{
    ViewBag.Title = "KategoriDuzenle";
}

<h2>Kategori Düzenle</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    
    <fieldset>
        
        <legend>Kategori</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor">
            @Html.LabelFor(model => model.Adi)
        </div>
        <div class="editor">
            @Html.EditorFor(model => model.Adi)
            @Html.ValidationMessageFor(model => model.Adi)
        </div>

        <p>
            <input type="submit" value="Kaydet" />
        </p>
    </fieldset>
    
}

<div>
    @Html.ActionLink("Listeye Dön", "Kategori")
</div>

MvcApplication3/Views/Yonetim/KategoriEkle.cshtml
@model MvcApplication3.Models.Kategori

@{
    ViewBag.Title = "KategoriEkle";
}

<h2>KategoriEkle</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Kategori Ekle</legend>

        <div class="editor-label">
           Kategori Adı:<br />
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Adi)
            @Html.ValidationMessageFor(model => model.Adi)
        </div>

        <p>
            <input class="btn btn-success" type="submit" value="Kaydet" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Listeye Dön", "Kategori")
</div>

MvcApplication3/Views/Yonetim/Rol.cshtml
@model MvcApplication3.Models.Kategori

@{
    ViewBag.Title = "Rol";
}

<h2>Rol</h2>